export const testUsernames: string[] = [
  'pinchethnic',
  'truffleyearning',
  'safedumbass',
  'helpfulfardage',
  'allowtrumpet',
  'choosecivilian',
  'overjoyedmangoes',
  'gerbilflaxseed',
  'frustratedrunner',
  'easterlypecans',
  'spectralquantity',
  'hypnoticvisual',
  'bollardhollow',
  'saddleinterview',
  'dyogramjackstay',
  'gogglessault',
  'datehalyard',
  'sturdyportion',
  'futureporch',
  'tragiccanary',
  'tailoramazon',
  'immatureguard',
  'amuckpicayune',
  'sedatenut',
  'tightsweatherly',
  'spotlesscashier',
  'fretsector',
  'itchdowdy',
  'kiteburritos',
  'offensehelp',
  'believefreak',
  'shawlanchored',
  'fastenchick',
  'remudagingerbread',
  'parrelapron',
  'unwrapratio',
  'klutzyleg',
  'mewsalso',
  'quartzmagpie',
  'shootimpressive',
  'fieldfrost',
  'noxiousbutterfly',
  'hilariousroach',
  'thousandbestow',
  'presentmuslin',
  'reflectiveflipflops',
  'lazycampaign',
  'hyundaigreater',
  'coralantler',
  'yieldforester',
  'shortsreal',
  'sympathizebore',
  'pinionexplain',
  'stoicblitzen',
  'accessmovie',
  'yokebonehead',
  'siegeusable',
  'handfuldingdong',
  'kapipaddleball',
  'emissioninquiry',
  'idiotaffirm',
  'mightyzzz',
  'audistriking',
  'endertractor',
  'bowterms',
  'blinkknockback',
  'knotpoppy',
  'shipdejected',
  'burritoreality',
  'lecternmore',
  'threadpintail',
  'sourcethere',
  'seahorsebring',
  'soccerbrush',
  'stretchfray',
  'costauk',
  'fletchingbid',
  'rolexgesture',
  'opulentproperty',
  'possessiveroll',
  'coterievegetable',
  'cakefarflung',
  'rotbiking',
  'skegfresh',
  'alienatedcite',
  'coalorewhine',
  'furtiveextension',
  'guardhospital',
  'ministeroptimism',
  'savannapie',
  'shirtesteemed',
  'erminemajor',
  'tipnancy',
  'psychonoteworthy',
  'pretendtamale',
  'revolvingteam',
  'articulatecolleague',
  'nidecost',
  'simplisticidentical',
  'postulateinject',
  'garlicminnow',
  'burnishedwindbound',
  'fruitmaterial',
  'negotiatemess',
  'ratioaustere',
  'punctualbicycle',
  'morningwhiting',
  'actuallyeroded',
  'polesmall',
  'suspendsip',
  'attendfemur',
  'medialrob',
  'insecuregam',
  'analystsizzle',
  'generosityquota',
  'jumpropeoptician',
  'duringcrazy',
  'glazedasset',
  'roachpickleball',
  'failuremultiple',
  'againcoffee',
  'stingythundering',
  'weeklylocked',
  'swallowvocal',
  'cropexactly',
  'agencyeasy',
  'backfinally',
  'youdutiful',
  'giftedstripe',
  'doorworthless',
  'personblissful',
  'plumbercelebrate',
  'appointcheeseburger',
  'threadbarechurch',
  'unselfishwrack',
  'cockroachextraneous',
  'presentsoriginally',
  'hopefulissue',
  'groovyfanatical',
  'breastunwilling',
  'heyfortunate',
  'calfjournalist',
  'cookingcobweb',
  'grainanimated',
  'frazzledpossess',
  'ludicrouscatcher',
  'cashewsunder',
  'choiceeconomy',
  'concededoes',
  'factoryannoy',
  'beltedmarrow',
  'asleepinfinity',
  'cameraemployer',
  'markprincipal',
  'panickyusurp',
  'turbulentphobic',
  'animatedcompete',
  'crocodilesick',
  'humdrumkooky',
  'willingpotato',
  'tyketrivial',
  'forelimbsuddenly',
  'termmidwife',
  'layfizzle',
  'surfingfibber',
  'frisbeevapor',
  'hardconsultant',
  'supremeemotion',
  'gracepan',
  'ostrichpointless',
  'deltoidspacesuit',
  'fastbittern',
  'westautomatic',
  'illogicalimportant',
  'lackingsupply',
  'debatefive',
  'creepyrout',
  'activeinitial',
  'thereweaver',
  'wheneverportray',
  'horizonfrom',
  'bulletdirectly',
  'sounderroomy',
  'honestproof',
  'clinkoperating',
  'dweebocelot',
  'mouthgirlfriend',
  'fumblingscreen',
  'trounceshoot',
  'majorforegoing',
  'silvergiggle',
  'physicalfoxglove',
  'allianzspokesman',
  'moobomb',
  'foresthistorian',
  'familypaver',
  'findingholistic',
  'evolveperceive',
  'hymnsing',
  'proteinjellied'
]
export const testMessages: string[] = [
  'The purple elephant dances on Tuesdays',
  'Singing in the rain with a toaster',
  'Writing love letters to a friendly ghost',
  'When life gives you lemons, make paper airplanes',
  'Lost in a sea of marshmallows',
  'Whispering secrets to the moon',
  "Tickling a dragon's tail with a feather",
  'Juggling porcupines in a thunderstorm',
  'Dancing with socks on a slippery floor',
  'The secret life of rubber ducks',
  'Flying kites on a windy day',
  'Unicorns racing through cotton candy fields',
  'Searching for treasure in a cereal box',
  'Painting the sky with polka dots',
  'Inventing a language only birds understand',
  'Breaking the rules of gravity',
  "Spinning in circles until you're dizzy",
  'Floating on a cloud made of marshmallows',
  'Whistling to the tune of a babbling brook',
  'The adventures of a purple banana',
  'Building castles out of sand in the living room',
  'Chasing rainbows with a butterfly net',
  'Playing hide and seek with a chameleon',
  'The magic of a talking teapot',
  'Climbing a ladder to the moon',
  'Sliding down a rainbow into a pot of gold',
  'The curious case of the disappearing socks',
  'Hopping on one foot while eating spaghetti',
  'When elephants learn to dance ballet',
  'Swimming with dolphins in a bathtub',
  'The art of balancing spoons on your nose',
  'Knitting sweaters for giraffes',
  'Baking cookies in the shape of planets',
  'Discovering a hidden door in the attic',
  'Sailing a paper boat on a puddle',
  'Reading bedtime stories to a friendly monster',
  'Wearing a top hat made of cheese',
  'The secret language of squirrels',
  'Skipping stones across the ocean',
  'The mystery of the singing flowers',
  'Playing hopscotch on a rainbow',
  'Dancing with fireflies in the moonlight',
  'Planting jellybeans and growing lollipops',
  'Talking to the stars through a tin can phone',
  'Solving a puzzle with invisible pieces',
  'Bouncing on a trampoline made of bubble wrap',
  'Taming wild unicorns with bubblegum',
  'Swinging from the branches of a cotton candy tree',
  'The amazing acrobatics of a juggling octopus',
  'Walking backwards through a maze',
  'Creating a symphony with rubber duckies',
  'Picking strawberries in a field of dreams',
  'When cats learn to play the piano',
  'Whispering secrets to a ladybug',
  'Building sandcastles in a snowstorm',
  'The upside-down adventures of a flying fish',
  'Jumping on a pogo stick to the moon',
  'Wearing sunglasses at night',
  'Dancing in the rain with a purple umbrella',
  'The mischievous antics of a sock-stealing gnome',
  'Tying a bowtie made of spaghetti',
  'Building a time machine out of cardboard boxes',
  'Writing love letters to a friendly ghost',
  'The magical powers of a talking tree',
  'Practicing yoga with a herd of elephants',
  'When clouds learn to play hide and seek',
  'Baking a cake in the shape of a smile'
]

export const longMessage = 'The magical powers of a talking tree, Practicing yoga with a herd of elephants, When clouds learn to play hide and seek, Baking a cake in the shape of a smile, The monkey wears a tuxedo to the beach'

export const testImages = [
  'https://go.kouna.io/-/D9_jM9eL',
  'https://go.kouna.io/-/aKMcVSw0',
  'https://go.kouna.io/-/mPbxjIBY',
  'https://go.kouna.io/-/Bq0JAyFR',
  'https://go.kouna.io/-/JaWN95J7',
  'https://go.kouna.io/-/i4ABDGTL',
  'https://go.kouna.io/-/Tk0p-9Yq',
  'https://go.kouna.io/-/auGx1wPK',
  'https://go.kouna.io/-/3YTGexz3',
  'https://go.kouna.io/-/nSyBVJoq',
  'https://go.kouna.io/-/kKi0iVmj',
  'https://go.kouna.io/-/4--4Gq-O',
  'https://go.kouna.io/-/zY-r39ze',
  'https://go.kouna.io/-/x8gPRwF7',
  'https://go.kouna.io/-/QSKYvolO',
  'https://go.kouna.io/-/pcY_I83l',
  'https://go.kouna.io/-/dsM4lcft',
  'https://go.kouna.io/-/0wa7-Isp',
  'https://go.kouna.io/-/QsWFPyuh',
  'https://go.kouna.io/-/UOBdhCFY',
  'https://go.kouna.io/-/Y9vJ4A1c',
  'https://go.kouna.io/-/XH3yPFG0',
  'https://go.kouna.io/-/XNCcidY4',
  'https://go.kouna.io/-/DPFWdry_',
  'https://go.kouna.io/-/4rBteaGw',
  'https://go.kouna.io/-/ROjwJYEh',
  'https://go.kouna.io/-/4d57NNBm',
  'https://go.kouna.io/-/nOe-o7Yf',
  'https://go.kouna.io/-/wxJ6Etxl',
  'https://go.kouna.io/-/gIaXH0p1',
  'https://go.kouna.io/-/LKlEIoiC',
  'https://go.kouna.io/-/cT3Hmkz-'
]
